# Welcome to Jekyll!
#

# Site settings
title: iPay
headline: |
  Integrated Payment Solution
description: iPay is an online payment processing solution and invoicing system for your business. It provides a free system integration and support to your shopping cart or web service.
logo: /images/ipay_logo.png
owner: Information Business # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ipay@ib.sa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ipay.sa" # the base hostname & protocol for your site
project-url: http://ib.sa/projects/ipay
contact-url: http://ib.sa/#contact
social:
  twitter: https://twitter.com/InforBizness
  github: https://github.com/iBizness
  linkedin-square: https://linkedin.com/company/information-business
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
prose:
  rooturl: "_data"
  #ignore: ['_config.yml','CNAME','feed.xml','index.html']
  siteurl: "http://ipay.sa"
  media: "images"
  metadata:
      features:
        - name: "header"
          field:
            element: "text"
            label: "Header"
        - name: "Intro"
          field:
            element: "textarea"
            label: "Introduction"
      items:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
      - name: "icon"
        field:
          element: "text"
          label: "Icon (from https://fortawesome.github.io/Font-Awesome/cheatsheet/)"
